name: studydegrees
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.2
  firebase_storage: ^11.0.5
  cloud_firestore: ^4.0.5
  flutter_native_splash: ^2.2.14
  introduction_screen: ^3.0.1
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  curved_navigation_bar: ^1.0.3
  another_flushbar: ^1.12.29
  get_storage: ^2.0.3
  pin_code_fields: ^7.4.0
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.4.2
  logger: ^1.1.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_launcher_icons: 0.10.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  icon_size: 40
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  assets:
    - assets/
    - assets/app/authimages/Signup/
    - assets/app/authimages/Login/
    - assets/app/startimages/
    - assets/app/choosetopic/
    - assets/app/home/

  uses-material-design: true

flutter_native_splash:
  color: '#ffffff'
  image: assets/icon.png
  android_12:
    image: assets/icon.png
    icon_background_color: '#ffffff'
  web: true

